### ISSUE TITLE
[Meta] Swift Actors Integration: Towards Pitch #1

### ISSUE THREAD

**Issue by ktoso** [apple/swift-distributed-actors#791]
### Pre-requisites

- [x] Swift Evolution Actors review
- [ ] Swift Evolution Actors review accepted...?
- [ ] Runtime component "needs" SwiftPM Extensible Build Tools to be "truly great"

#### Design status

- [x] General outline is solid, we've proven it with `Actorable` before

#### Implementation status

[rdar://70840120](rdar://70840120) (🐟 Integrate Distributed Actors with Swift Actors)

- [x] type checking `distributed actor` isolation
  - [x] disallow access to properties
  - [x] disallow access to any non-`distributed` functions from outside
  - [x] allow conforming to sync protocol, in order to conform to `Codable`
    - do we allow `@actorIndependent(unsafe)` distributed funcs to be invoked? Probably needs some more design or another unsafe style attribute...?
    - [x] implement internal `@_distributedActorIndependent` attribute and apply to `let actorAddress`
      - [x] it is usable from everywhere, without "is local" checks
  - [ ] maybe works: disallow access to `@actorIndependent(unsafe)` properties
  - [ ] subclassing -- will we have subclassing or not really?
- [x] type checking `distributed func`
  - [x] may only be defined within distributed actors
  - [ ] may be defined in distributed actor protocols
  - [x] FIXME: currently require being async and throws
    - [ ] Instead: make implicitly throws and async when invoked from outside of actor.
  - [x] all paramter types must be `Codable`
  - [x] return type must be `Codable` or `Void`
  - [x] allow `distributed func <T: Codable>test(t: T)` - seems to need special handling
  - [x] allow `distributed func <T: Codable>test() -> T` - seems to need special handling
- [x] Define `DistributedActor` protocol
  - [ ] ensure it is not possible to conform to it manually
    - [ ] this isn't even done for normal actors yet; so we'll ride on however it will be done there once it is
  - [ ] FOR NOW, forbid other protocols conforming to `DistributedActor` protocol as well -- we'll lift this in the future
- [x] Define `ActorTransport` protocol
- [x] ActorAddress definition
  - [ ] Define `ActorAddress` as nice struct that that is URI like and all transports should be able to use
    - @drexin has some great ideas on optimal representations
- [x] Simple synthesis tasks
  - [x] synthesize stored property `let address: ActorAddress` 
  - [x] synthesize stored property `let transport: ActorTranspor` 
- [x] :construction: synthesize `init(transport:)` 
  - [x] enforce that all other inits must call into it
  - [x] make it impossible to define your own of the same shape
- [x] :construction: synthesize `init(resolve:using)` 
  - [x] enforce it is impossible to delegate to it
  - [x] make it impossible to define your own of the same shape
- [ ] add `transport.resignAddress()` to distributed actor deinit
- [ ] `Codable` conformance by encoding/decoding `ActorAddress`
  - may not necessarily need synthesis, just extension on the DistributedActor protocol :thinking:
  - Actually invoking it may require `withLocalActor`
- [ ] "Proxy Actor Instance" (**the hardest part**)
  - [ ] :construction: synthesize `init(resolve:using:)` resolve initializer
  - [ ] special "proxy instance" allocation, must only allocate enough memory for the address and transport, do not allocate for any of the real properties
  - [x] marker "bit" in Actor types to demark that the instance is a "proxy" @ktoso 
  - [x] marker bit setting/initializing function @ktoso 
  - [x] querying the bit using `isDistributedRemote` @ktoso 
  - [ ] set the bit when we create a "remote" instance
- [x] synthesis: bodies to call `if __isRemoteActor(self) { $distributed_...(...) }``
- [ ] `withLocalActor` can be introduced later on perhaps?
  - :warning: We likely need it wrt to invoking synchronous functions such as Codable stuff though
    - it returns `{ (actor Self) in ... }`which is the same instance, but known to be a local actor
- [ ] Global actors must not be distributed
- [ ] 
#### Can be Scoped-out

- [ ] `protocol X: DistributedActor` which are "**service definitions**"
  - We don't strictly need it for distributed to already be useful, 
  - It's harder to implement than just the "Proxy Actor Instance"
  - CloudKit Functions, if they are convienced to use Swift more, could have specific requirements here...?

#### Sakkana "rebase"

- [ ] Remove all of executor infrastructure, replace with Swift Actors,
- [ ] Pretty worried about lack of uni-directional messages in the Swift programming model...
  - [ ] We might need to do something about this,
- [ ] APIs that are likely not possible to express using Swift Actors will be dropped:
  - [ ] e.g. our `@ActorOwned CRDT` types
    - Expressible iff Swift gets "**assistant actor** types" how John called them initially
  - [ ] Actor names are gone
    - [ ] Swift does not enforce names or trees, we can't rely on them anymore
    - [ ] May need some protocols or patterns to replicate it, or we'll have a very hard time debugging systems in this new runtime
  - [ ] Supervision trees are gone
    - [ ] and need a complete redesign, more around concepts like "link", we can express it with enough protocols and smarts I think...

- [ ] Rephrase project as "transport" or runtime, rather than the whole package

- [ ] Other features we have to drop:

  - [ ] Swift Actors can't make use of Swift Metrics as well as Sakkana used to, we'll have to drop this integration
  - [ ] Customizable executors; we'll have to rely on Swift's story here

----

### Pre-requisites

- Full "new" implementation depends on:
  - [ ] [rdar://70546948](rdar://70546948) (Leverage thread-local storage for the current task)
    - [ ] whch enables Structured Concurrency's new APIs, including `Task.unsafeCurrent`
  - [ ] Structured Concurrency being reviewed

### Timing...?

- How can we make sure this ships in Sunriver given M3-dev ends February 19th
  - will Structured Concurrency be reviewed in-time for this to get a review and land?
